/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2~PC34
 */
public class zonn extends javax.swing.JFrame {

    /**
     * Creates new form zonn
     */
    public zonn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 134, 210, 30));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 176, 210, 30));

        jLabel1.setText("Player 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 141, 64, -1));

        jLabel2.setText("Player 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 183, 64, -1));

        btn1.setText("vs");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 224, 171, 33));

        txt3.setText("5");
        txt3.setEnabled(false);
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 210, 30));

        txt4.setText("5");
        txt4.setEnabled(false);
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 210, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("3");
        jLabel3.setToolTipText("");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 20, 20));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("1");
        jLabel4.setToolTipText("");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 20, 20));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("2");
        jLabel5.setToolTipText("");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 20, 20));

        jLabel6.setText("scissor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 80, 30));

        jLabel7.setText("rock");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 80, 30));

        jLabel8.setText("paper");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 80, 30));

        jLabel9.setText("player2");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        jLabel10.setText("player1");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jButton1.setText("hello world");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
int player1 = Integer.parseInt(txt1.getText());
int player2 = Integer.parseInt(txt2.getText());
int hb1 = Integer.parseInt(txt3.getText());
int hb2 = Integer.parseInt(txt4.getText());

int asd1 = hb1 - 1;
int asd2 = hb2 - 1;


if (player1 == 1 && player2 == 1)
{      
    JOptionPane.showMessageDialog(null,"Draw","VS", HEIGHT);
}
else if (player1 == 1 && player2 == 2)
{
    txt3.setText("" + asd1);
    
    JOptionPane.showMessageDialog(null,"Player 2 Win","VS", HEIGHT);
}
else if (player1 == 1 && player2 == 3)
{
    txt4.setText("" + asd2);
    
    JOptionPane.showMessageDialog(null,"Player 1 Win","VS", HEIGHT);
}    
else if (player1 == 2 && player1 == 1)
{
    txt3.setText("" + asd1);
    
    JOptionPane.showMessageDialog(null,"Player 2 Win","VS", HEIGHT);
}
else if (player1 == 2 && player2 == 2)
{   
    JOptionPane.showMessageDialog(null,"Draw","VS", HEIGHT);
}    
else if (player1 == 2 && player2 == 3)
{
    txt4.setText("" + asd2);
    
    JOptionPane.showMessageDialog(null,"Player 2 Win","VS", HEIGHT);
}
else if (player1 == 3 && player2 == 1)
{
    txt3.setText("" + asd1);
    
    JOptionPane.showMessageDialog(null,"Player 1 Win","VS", HEIGHT);
}    
else if (player1 == 3 && player2 == 2)
{
    txt4.setText("" + asd2);
    
    JOptionPane.showMessageDialog(null,"Player 2 Win","VS", HEIGHT);
}
else if (player1 == 3 && player2 == 3)
{    
    JOptionPane.showMessageDialog(null,"Draw","VS", HEIGHT);
}    
else 
{
    JOptionPane.showMessageDialog(null,"INVALID","INVALID",JOptionPane.INFORMATION_MESSAGE);

}
    
    }//GEN-LAST:event_btn1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
        new zonn1().show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(zonn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(zonn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(zonn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(zonn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new zonn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    // End of variables declaration//GEN-END:variables
}
